# 📊 Pandas EAD 1 - Introdução ao Pandas

Este notebook é uma introdução à biblioteca **Pandas**, a ferramenta mais poderosa para análise de dados em Python.

## 📚 Conceitos abordados:
- O que é o Pandas?
- Instalação e importação
- Estruturas principais: Series e DataFrame
- Criando DataFrames
- Visualizando dados
- Selecionando colunas
- Estatísticas básicas

## 🎯 Objetivo:
Ao final deste módulo, você será capaz de criar e manipular DataFrames básicos no Pandas.

**Vamos começar!** 🚀

## 1. O que é o Pandas?

Pandas é uma biblioteca Python que fornece estruturas de dados de alta performance e ferramentas de análise de dados.

### Principais estruturas:

1. **Series**: Array unidimensional (uma coluna)
2. **DataFrame**: Estrutura bidimensional (tabela com linhas e colunas)

### Por que usar Pandas?
- ✅ Fácil manipulação de dados tabulares
- ✅ Leitura/escrita de diversos formatos (CSV, Excel, SQL, JSON)
- ✅ Limpeza e preparação de dados
- ✅ Análise estatística rápida
- ✅ Integração com outras bibliotecas (NumPy, Matplotlib)

## 2. Instalação e Importação

### Instalação (se necessário):
```bash
pip install pandas
```

### Importação:
O padrão é importar o pandas como `pd`:

In [0]:
import pandas as pd

# Verificando a versão
print(f"Versão do Pandas: {pd.__version__}")

## 3. Series - A Estrutura Unidimensional

Uma Series é como uma coluna de dados. Pode ser criada a partir de uma lista, dicionário ou array NumPy.

In [0]:
# Criando uma Series a partir de uma lista
notas = pd.Series([8, 9, 7, 10, 6])
print(notas)
print("\n" + "="*40)
print(f"Média: {notas.mean()}")
print(f"Máximo: {notas.max()}")
print(f"Mínimo: {notas.min()}")

## 4. DataFrame - A Estrutura Bidimensional

Um DataFrame é como uma planilha ou tabela SQL. É a estrutura mais usada no Pandas.

In [0]:
# Criando um DataFrame a partir de um dicionário
dados = {
    'Nome': ['Ana', 'João', 'Maria', 'Pedro', 'Carla'],
    'Idade': [25, 30, 28, 35, 22],
    'Cidade': ['São Paulo', 'Rio', 'Belo Horizonte', 'Curitiba', 'Salvador'],
    'Nota': [8.5, 9.0, 7.5, 9.5, 8.0]
}

df = pd.DataFrame(dados)
print(df)

## 5. Visualizando Dados

O Pandas oferece várias formas de visualizar os dados:

In [0]:
# Visualizando as primeiras linhas
print("Primeiras 3 linhas:")
print(df.head(3))

print("\nÚltimas 2 linhas:")
print(df.tail(2))

print("\nInformações do DataFrame:")
print(df.info())

print("\nEstatísticas descritivas:")
print(df.describe())

## 6. Selecionando Colunas

Você pode selecionar colunas de várias formas:

In [0]:
# Selecionando uma coluna (retorna uma Series)
print("Coluna Nome:")
print(df['Nome'])

print("\nMúltiplas colunas (retorna um DataFrame):")
print(df[['Nome', 'Nota']])

## 7. Adicionando Nova Coluna

É muito fácil adicionar novas colunas a um DataFrame:

In [0]:
# Adicionando uma coluna de status (aprovado/reprovado)
df['Status'] = df['Nota'].apply(lambda x: 'Aprovado' if x >= 7 else 'Reprovado')
print(df)

## 8. Exercícios - Nível 1

Agora é sua vez! Resolva os exercícios abaixo para fixar os conceitos básicos do Pandas.

### Exercício 1: Criando um DataFrame
Crie um DataFrame com os seguintes dados de produtos:
- Produtos: ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Headset']
- Preços: [2500, 80, 200, 1200, 300]
- Quantidade: [10, 50, 30, 15, 40]

Calcule o valor total em estoque (preço * quantidade) para cada produto e adicione como uma nova coluna.

In [1]:
# Seu código aqui
import pandas as pd
# Seu código aqui
dados = { 
    'Produtos': ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Headset'],
    'Preços': [2500, 80, 200, 1200, 300],
    'Quantidade': [10, 50, 30, 15, 40]
}
df = pd.DataFrame(dados)
df

   Produtos  Preços  Quantidade
0  Notebook    2500          10
1     Mouse      80          50
2   Teclado     200          30
3   Monitor    1200          15
4   Headset     300          40

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Produtos    5 non-null      str
 1   Preços      5 non-null      int64
 2   Quantidade  5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 286.0 bytes

In [3]:
df['valor total em estoque'] = df['Preços'] * df['Quantidade']
df

   Produtos  Preços  Quantidade  valor total em estoque
0  Notebook    2500          10                   25000
1     Mouse      80          50                    4000
2   Teclado     200          30                    6000
3   Monitor    1200          15                   18000
4   Headset     300          40                   12000

### Exercício 2: Visualizando Dados
Use o DataFrame criado no exercício anterior e:
1. Mostre as 3 primeiras linhas
2. Mostre as estatísticas descritivas
3. Mostre apenas os produtos com preço > 500

In [4]:
# Seu código aqui
print("Primeiras 3 linhas:")
print(df.head(3))

Primeiras 3 linhas:
   Produtos  Preços  Quantidade  valor total em estoque
0  Notebook    2500          10                   25000
1     Mouse      80          50                    4000
2   Teclado     200          30                    6000

In [5]:
print("\nEstatísticas descritivas:")
print(df.describe())

Estatísticas descritivas:
            Preços  Quantidade  valor total em estoque
count     5.000000    5.000000                5.000000
mean    856.000000   29.000000            13000.000000
std    1020.137246   16.733201             8660.254038
min      80.000000   10.000000             4000.000000
25%     200.000000   15.000000             6000.000000
50%     300.000000   30.000000            12000.000000
75%    1200.000000   40.000000            18000.000000
max    2500.000000   50.000000            25000.000000

In [6]:
df[df['Preços'] >500]

   Produtos  Preços  Quantidade  valor total em estoque
0  Notebook    2500          10                   25000
3   Monitor    1200          15                   18000

### Exercício 3: Series e Métodos Básicos
Crie uma Series com as idades de 10 pessoas. Calcule e imprima:
- Média das idades
- Mediana
- Desvio padrão
- Idade máxima e mínima
- Número total de elementos

In [7]:
# Seu código aqui
idades = pd.Series([10, 11, 13, 15, 16, 17, 20, 22, 26, 28])
print(idades)

0    10
1    11
2    13
3    15
4    16
5    17
6    20
7    22
8    26
9    28
dtype: int64

In [8]:
print(f"Media: {idades.mean()}")
print(f"Maximo: {idades.max()}")
print(f"Minimo: {idades.min()}")
print(f"Desvio padrao: {idades.std()}")
print(f"Numero total de elementos: {idades.count()}")

Media: 17.8
Maximo: 28
Minimo: 10
Desvio padrao: 6.106462878695726
Numero total de elementos: 10

### Exercício 4: DataFrame a partir de Lista
Crie um DataFrame a partir de uma lista de listas:
```python
dados = [
    ['Ana', 25, 'SP', 8.5],
    ['João', 30, 'RJ', 9.0],
    ['Maria', 28, 'BH', 7.5]
]
```
Defina os nomes das colunas como ['Nome', 'Idade', 'Cidade', 'Nota'].

In [9]:
# Seu código aqui
dados = {
    'Nome': ['Ana', 'João', 'Maria'],
    'Idade': [25, 30, 28],
    'Cidade': ['São Paulo', 'Rio', 'Belo Horizonte'],
    'Nota': [8.5, 9.0, 7.5]
}

df = pd.DataFrame(dados)
print(df)

    Nome  Idade          Cidade  Nota
0    Ana     25       São Paulo   8.5
1   João     30             Rio   9.0
2  Maria     28  Belo Horizonte   7.5

### Exercício 5: Adicionando Colunas
Baseado no DataFrame do exercício 4, adicione:
1. Uma coluna 'Dobro da Idade'
2. Uma coluna 'Nota + 1'

In [0]:
# Seu código aqui
df["Dobro de Idade"] = df["Idade"] * 2
df["Nota + 1"] = df["Nota"] + 1
print(df)